{{- if .Values.forwarder.localLogging }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-logging
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
  namespace: {{ .Values.app.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.forwarder.localLogging.storageSpace }}
  storageClassName: {{ .Values.forwarder.localLogging.storageClass }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}