apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Release.Name }}-clientSecret
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  clientSecret: {{ .Values.auth.clientSecret | b64enc | quote }}