apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-slave
  labels:
    app: {{ .Release.Name }}
    component: slave
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}
    component: master
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.ports.graylog.internal.port }}
  clusterIP: None