apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
    component: secret
    release: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.graylog.startupPassword | b64enc | quote }}
  passwordsha: {{ .Values.graylog.startupPassword | sha256sum | b64enc | quote }}
  mongoPassword: {{ index .Values "mongodb-replicaset" "auth" "adminPassword"  | b64enc | quote }}
  

