apiVersion: v1
name: graylog
version: 0.1.12
description: This Umbrella Helm Chart deploys Graylog, with a MongoDB ReplicaSet & HA Elasticsearch Cluster backend.
keywords:
  - graylog
  - mongodb
  - elasticsearch
  - siem
maintainers:
  - name: Chris Bosman
    email: christopher.r.bosman@gmail.com
appVersion: 1.0.0