apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app.name }}-policy
spec:
  podSelector:
    matchLabels: 
      app: {{ .Values.app.name }}
  policyTypes:
  - Egress
  - Ingress
  egress: []
  ingress:
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 80
      - 443