apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.registry }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        strategy:
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
        ports:
          - containerPort: {{ .Values.ports.internal }}
            name: app-port
      imagePullSecrets:
      - name: docker-auth